apiVersion: argoproj.io/v1alpha1               # Create a rollout resource
kind: Rollout
metadata:
  name: hello-kubernetes
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-kubernetes
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: hello-kubernetes
  strategy:
    blueGreen:
      activeService: hello-kubernetes-active
      previewService: hello-kubernetes-preview
      autoPromotionEnabled: false
      # previewReplicaCount: 1